version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel_app
    container_name: laravel_app
    ports:
      - "9000:9000"  # Port PHP-FPM
    volumes:
      - .:/var/www/html
    networks:
      - laravel

  webserver:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8081:80"  # Port Nginx untuk diakses dari browser
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8082:8080"  # Port Adminer untuk akses dari browser
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata:
